# Generated by Django 4.2.16 on 2024-12-11 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myweb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_site', models.CharField(max_length=250, unique=True)),
                ('imge', models.ImageField(blank=True, upload_to='images')),
                ('details', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(max_length=250)),
                ('dates', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Web_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('img', models.ImageField(blank=True, upload_to='images')),
                ('contacts', models.TextField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=250)),
                ('type_of_website', models.TextField(max_length=1000)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
