# Generated by Django 4.2.16 on 2024-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myweb',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='website',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='myweb',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='web_project',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
